In [122]:
import pandas as pd
from google.colab import drive
import numpy as np
import pandas as pd
import matplotlib as plt

from sklearn.linear_model import LinearRegression

drive.mount('/content/drive')
ruta = "/content/drive/MyDrive/Lasallista/tercer parcial/Datos.csv"

datos = pd.read_csv(ruta, sep=";")

datos

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

     Año     CO2   PIB anual Salario Minimo   Población
0   2020  90,252  237.746 M€     877.803,00  50.372.000
1   2019  92,623  288.857 M€     828.116,00  49.396.000
2   2018  86,459  282.916 M€     781.242,00  48.258.000
3   2017  83,015  276.082 M€     737.717,00  47.419.000
4   2016  95,398  255.416 M€     689.454,00  46.830.000
5   2015  85,452  264.527 M€     644.350,00  46.314.000
6   2014  85,363  286.971 M€     616.000,00  45.866.000
7   2013   82.44  287.699 M€     589.500,00  45.435.000
8   2012  72,908  288.520 M€     566.700,00  45.002.000
9   2011  72,452  240.636 M€     535.600,00  44.553.000
10  2010   66,82  216.111 M€     515.000,00  44.086.000
11  2009  65,239  166.668 M€     496.900,00  43.609.000
12  2008  62,009  164.879 M€     461.500,00  43.134.000
13  2007   61,48  150.478 M€     433.700,00  42.659.000
14  2006  59,764  128.857 M€     408.000,00  42.170.000
15  2005  60,917  117.033 M€     381.500,00  41.672.000
16  2004  58,669   93.525 M€     358.000,00  41.166.000
17  2003  58,538   83.128 M€     332.000,00  40.661.000
18  2002  59,013  102.911 M€     309.000,00  40.156.000
19  2001  61,385         NaN     286.000,00  39.656.000
20  2000  61,707  107.438 M€     260.100,00  39.152.000
21  1999   59,26   96.726 M€     236.460,00  38.573.000
22  1998  67,547    85.96 M€     203.826,00  38.088.000
23  1997   66,73         NaN     172.005,00  37.505.000
24  1996  61,055    84,12 M€     142.125,00  37.019.000
25  1995  61,829         NaN     118.934,00  36.426.000

In [123]:
datos["PIB anual"] = datos["PIB anual"].str.replace("M€", " ")
datos["Salario Minimo"] = datos["Salario Minimo"].str.replace(",00", " ")

datos

     Año     CO2  PIB anual Salario Minimo   Población
0   2020  90,252  237.746         877.803   50.372.000
1   2019  92,623  288.857         828.116   49.396.000
2   2018  86,459  282.916         781.242   48.258.000
3   2017  83,015  276.082         737.717   47.419.000
4   2016  95,398  255.416         689.454   46.830.000
5   2015  85,452  264.527         644.350   46.314.000
6   2014  85,363  286.971         616.000   45.866.000
7   2013   82.44  287.699         589.500   45.435.000
8   2012  72,908  288.520         566.700   45.002.000
9   2011  72,452  240.636         535.600   44.553.000
10  2010   66,82  216.111         515.000   44.086.000
11  2009  65,239  166.668         496.900   43.609.000
12  2008  62,009  164.879         461.500   43.134.000
13  2007   61,48  150.478         433.700   42.659.000
14  2006  59,764  128.857         408.000   42.170.000
15  2005  60,917  117.033         381.500   41.672.000
16  2004  58,669   93.525         358.000   41.166.000
17  2003  58,538   83.128         332.000   40.661.000
18  2002  59,013  102.911         309.000   40.156.000
19  2001  61,385        NaN       286.000   39.656.000
20  2000  61,707  107.438         260.100   39.152.000
21  1999   59,26   96.726         236.460   38.573.000
22  1998  67,547    85.96         203.826   38.088.000
23  1997   66,73        NaN       172.005   37.505.000
24  1996  61,055    84,12         142.125   37.019.000
25  1995  61,829        NaN       118.934   36.426.000

In [124]:
datos["PIB anual"] = datos["PIB anual"].str.replace(",", ".")
datos["CO2"] = datos["CO2"].str.replace(",", ".")
datos["Población"] = datos["Población"].str.replace(".", "")
datos

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  This is separate from the ipykernel package so we can avoid doing imports until

     Año     CO2  PIB anual Salario Minimo Población
0   2020  90.252  237.746         877.803   50372000
1   2019  92.623  288.857         828.116   49396000
2   2018  86.459  282.916         781.242   48258000
3   2017  83.015  276.082         737.717   47419000
4   2016  95.398  255.416         689.454   46830000
5   2015  85.452  264.527         644.350   46314000
6   2014  85.363  286.971         616.000   45866000
7   2013   82.44  287.699         589.500   45435000
8   2012  72.908  288.520         566.700   45002000
9   2011  72.452  240.636         535.600   44553000
10  2010   66.82  216.111         515.000   44086000
11  2009  65.239  166.668         496.900   43609000
12  2008  62.009  164.879         461.500   43134000
13  2007   61.48  150.478         433.700   42659000
14  2006  59.764  128.857         408.000   42170000
15  2005  60.917  117.033         381.500   41672000
16  2004  58.669   93.525         358.000   41166000
17  2003  58.538   83.128         332.000   40661000
18  2002  59.013  102.911         309.000   40156000
19  2001  61.385        NaN       286.000   39656000
20  2000  61.707  107.438         260.100   39152000
21  1999   59.26   96.726         236.460   38573000
22  1998  67.547    85.96         203.826   38088000
23  1997   66.73        NaN       172.005   37505000
24  1996  61.055    84.12         142.125   37019000
25  1995  61.829        NaN       118.934   36426000

In [125]:
#Limpieza de datos

datos["PIB anual"] = datos["PIB anual"].fillna(0)

#variable dependiente: Salario mínimo; variables independientes: PIB anual,
#población y CO2

datos

     Año     CO2  PIB anual Salario Minimo Población
0   2020  90.252  237.746         877.803   50372000
1   2019  92.623  288.857         828.116   49396000
2   2018  86.459  282.916         781.242   48258000
3   2017  83.015  276.082         737.717   47419000
4   2016  95.398  255.416         689.454   46830000
5   2015  85.452  264.527         644.350   46314000
6   2014  85.363  286.971         616.000   45866000
7   2013   82.44  287.699         589.500   45435000
8   2012  72.908  288.520         566.700   45002000
9   2011  72.452  240.636         535.600   44553000
10  2010   66.82  216.111         515.000   44086000
11  2009  65.239  166.668         496.900   43609000
12  2008  62.009  164.879         461.500   43134000
13  2007   61.48  150.478         433.700   42659000
14  2006  59.764  128.857         408.000   42170000
15  2005  60.917  117.033         381.500   41672000
16  2004  58.669   93.525         358.000   41166000
17  2003  58.538   83.128         332.000   40661000
18  2002  59.013  102.911         309.000   40156000
19  2001  61.385          0       286.000   39656000
20  2000  61.707  107.438         260.100   39152000
21  1999   59.26   96.726         236.460   38573000
22  1998  67.547    85.96         203.826   38088000
23  1997   66.73          0       172.005   37505000
24  1996  61.055    84.12         142.125   37019000
25  1995  61.829          0       118.934   36426000

In [127]:
datos = datos.astype({'PIB anual': float, 'CO2':float, 'Salario Minimo':float, 'Población':int} )
datos

     Año     CO2  PIB anual  Salario Minimo  Población
0   2020  90.252    237.746         877.803   50372000
1   2019  92.623    288.857         828.116   49396000
2   2018  86.459    282.916         781.242   48258000
3   2017  83.015    276.082         737.717   47419000
4   2016  95.398    255.416         689.454   46830000
5   2015  85.452    264.527         644.350   46314000
6   2014  85.363    286.971         616.000   45866000
7   2013  82.440    287.699         589.500   45435000
8   2012  72.908    288.520         566.700   45002000
9   2011  72.452    240.636         535.600   44553000
10  2010  66.820    216.111         515.000   44086000
11  2009  65.239    166.668         496.900   43609000
12  2008  62.009    164.879         461.500   43134000
13  2007  61.480    150.478         433.700   42659000
14  2006  59.764    128.857         408.000   42170000
15  2005  60.917    117.033         381.500   41672000
16  2004  58.669     93.525         358.000   41166000
17  2003  58.538     83.128         332.000   40661000
18  2002  59.013    102.911         309.000   40156000
19  2001  61.385      0.000         286.000   39656000
20  2000  61.707    107.438         260.100   39152000
21  1999  59.260     96.726         236.460   38573000
22  1998  67.547     85.960         203.826   38088000
23  1997  66.730      0.000         172.005   37505000
24  1996  61.055     84.120         142.125   37019000
25  1995  61.829      0.000         118.934   36426000

In [128]:
#Matriz de correlación
print (datos.corr())

                     Año       CO2  PIB anual  Salario Minimo  Población
Año             1.000000  0.839580   0.920650        0.995060   0.997013
CO2             0.839580  1.000000   0.796227        0.849805   0.834125
PIB anual       0.920650  0.796227   1.000000        0.897288   0.902929
Salario Minimo  0.995060  0.849805   0.897288        1.000000   0.998426
Población       0.997013  0.834125   0.902929        0.998426   1.000000

In [150]:
#Modelo de regresión con 1 variable
import statsmodels.formula.api as smf
from patsy.builtins import *

r1 = smf.ols(formula = 'Q("Salario Minimo")~Población', data=datos).fit()

r1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     Q("Salario Minimo")   R-squared:                       0.997
Model:                             OLS   Adj. R-squared:                  0.997
Method:                  Least Squares   F-statistic:                     7605.
Date:                 Thu, 24 Nov 2022   Prob (F-statistic):           1.52e-31
Time:                         00:12:03   Log-Likelihood:                -101.44
No. Observations:                   26   AIC:                             206.9
Df Residuals:                       24   BIC:                             209.4
Df Model:                            1
Covariance Type:             nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1904.7845     27.236    -69.937      0.000   -1960.996   -1848.573
Población   5.515e-05   6.32e-07     87.209      0.000    5.38e-05    5.65e-05
==============================================================================
Omnibus:                        1.910   Durbin-Watson:                   0.355
Prob(Omnibus):                  0.385   Jarque-Bera (JB):                1.699
Skew:                           0.547   Prob(JB):                        0.428
Kurtosis:                       2.391   Cond. No.                     4.80e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.8e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [151]:
#Modelo de regresión con 2 variables
import statsmodels.formula.api as smf
from patsy.builtins import *

r2 = smf.ols(formula = 'Q("Salario Minimo")~Población+Año', data=datos).fit()

r2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     Q("Salario Minimo")   R-squared:                       0.997
Model:                             OLS   Adj. R-squared:                  0.997
Method:                  Least Squares   F-statistic:                     3673.
Date:                 Thu, 24 Nov 2022   Prob (F-statistic):           1.53e-29
Time:                         00:12:06   Log-Likelihood:                -101.34
No. Observations:                   26   AIC:                             208.7
Df Residuals:                       23   BIC:                             212.5
Df Model:                            2
Covariance Type:             nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1620.4035   8261.982      0.196      0.846   -1.55e+04    1.87e+04
Población    5.87e-05   8.33e-06      7.045      0.000    4.15e-05    7.59e-05
Año           -1.8317      4.293     -0.427      0.674     -10.713       7.049
==============================================================================
Omnibus:                        2.443   Durbin-Watson:                   0.386
Prob(Omnibus):                  0.295   Jarque-Bera (JB):                2.033
Skew:                           0.662   Prob(JB):                        0.362
Kurtosis:                       2.647   Cond. No.                     1.43e+11
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+11. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [152]:
#Modelo de regresión con 3 variables
import statsmodels.formula.api as smf
from patsy.builtins import *

r3 = smf.ols(formula = 'Q("Salario Minimo")~Población+Q("PIB anual")+Año', data=datos).fit()

r3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     Q("Salario Minimo")   R-squared:                       0.997
Model:                             OLS   Adj. R-squared:                  0.997
Method:                  Least Squares   F-statistic:                     2399.
Date:                 Thu, 24 Nov 2022   Prob (F-statistic):           8.13e-28
Time:                         00:12:09   Log-Likelihood:                -101.03
No. Observations:                   26   AIC:                             210.1
Df Residuals:                       22   BIC:                             215.1
Df Model:                            3
Covariance Type:             nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept      -3169.4215   1.06e+04     -0.298      0.768   -2.52e+04    1.89e+04
Población       5.519e-05    9.7e-06      5.691      0.000    3.51e-05    7.53e-05
Q("PIB anual")    -0.0562      0.077     -0.729      0.474      -0.216       0.104
Año                0.6338      5.501      0.115      0.909     -10.775      12.043
==============================================================================
Omnibus:                        2.262   Durbin-Watson:                   0.372
Prob(Omnibus):                  0.323   Jarque-Bera (JB):                1.978
Skew:                           0.624   Prob(JB):                        0.372
Kurtosis:                       2.481   Cond. No.                     1.82e+11
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.82e+11. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
#Modelo mas representativo
"""
El modelo mas representativo es el primero (Salario mínimo con población).

Esto porque su estadístico F es mayor que los otros modelos, además, su
probabilidad de estadístico F de 1.52e-31 muestra que es un valor bastante
bueno para trabajar con el, a parte es el único modelo con intercepto T menor que
0.5, lo que lo hace mucho mas viable para trabajar en el

Además, tiene menos variables, por lo cual es mas fácil de utilizar.
"""